// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dpvarlxjennfhnubuveb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRwdmFybHhqZW5uZmhudWJ1dmViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNzY1NzMsImV4cCI6MjA2ODk1MjU3M30.SXEAmOwcF1OasUhLyoIGuhPwH_hrG0i2z8wE-DLAbjo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});